services:
  postgres:
    # image: postgres:9.2.24
    image: postgres:latest
    container_name: ssl-with-pgsql-open-ssl
    restart: unless-stopped
    environment:
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./certs:/etc/ssl/postgresql
    command: >
      postgres -c ssl=on
               -c ssl_cert_file=/etc/ssl/postgresql/server.crt
               -c ssl_key_file=/etc/ssl/postgresql/server.key
               -c ssl_ca_file=/etc/ssl/postgresql/rootCA.crt

    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
